version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes: 
      # -data:/data/db:ro
      - data:/data/db
    env_file:
      - ./secrets.env
  backend:
    build: ./backend
    ports: 
      - '80:8080'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_USERNAME=drew
      - MONGODB_PASSWORD=secret
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: 
